### PR TITLE
support custom/multiple prisma service

### PR DESCRIPTION
**Pull request by marcjulian**
Use custom location for your `PrismaClient` and import multiple at the same time.

Update to

```
npm i nestjs-prisma@0.20.0-dev.1
```

1. Add `output` to the client generator in your `schema.prisma` file to change the [prisma client location](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#the-location-of-prisma-client)

```schema.prisma
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

generator client {
  provider = "prisma-client-js"
  output = "../node_modules/@notiz/prisma" // 👈 choose the output directory
}

model User {
  id    String  @id @default(cuid())
  email String  @unique
  name  String?
}
```

2. Import `CustomPrismaModule` and provide a unique name and an instance of `PrismaClient`

```ts
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';

import { PrismaClient } from '@notiz/prisma'; // 👈 update to your output directory
import { CustomPrismaModule } from 'nestjs-prisma';

@Module({
  imports: [
    CustomPrismaModule.forRoot({
      name: 'PrismaServiceAuth', // 👈 must be unique for each PrismaClient
      client: new PrismaClient(),
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

3. Use `CustomPrismaService` and specify the used `PrismaClient` for the correct types

```ts
import { Inject, Injectable } from '@nestjs/common';

import { PrismaClient } from '@notiz/prisma';  // 👈 update to your output directory
import { CustomPrismaService } from 'nestjs-prisma';

@Injectable()
export class AppService {
  constructor(
    @Inject('PrismaServiceAuth') // 👈 use unique name to reference
    private prisma: CustomPrismaService<PrismaClient>,
  ) {}

  users() {
    return this.prisma.client.user.findMany();
  }

  user(userId: string) {
    return this.prisma.client.user.findFirstOrThrow({
      where: { id: userId },
    });
  }
}
```

4. If you have multiple `PrismaClient`s repeat step 2 and 3

```ts
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';

import { PrismaClient as PrismaAuth } from '@notiz/prisma'; // 👈 update to your output directory
import { PrismaClient as PrismaCms } from '@notiz/prisma-cms'; // 👈 update to your output directory
import { CustomPrismaModule } from 'nestjs-prisma';

@Module({
  imports: [
    CustomPrismaModule.forRoot({
      name: 'PrismaServiceAuth', // 👈 must be unique for each PrismaClient
      client: new PrismaAuth(),
    }),
    CustomPrismaModule.forRoot({
      name: 'PrismaServiceCms', // 👈 must be unique for each PrismaClient
      client: new PrismaCms(),
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

```ts
import { Inject, Injectable } from '@nestjs/common';

import { PrismaClient  as PrismaAuth} from '@notiz/prisma';  // 👈 update to your output directory
import { PrismaClient as PrismaCms } from '@notiz/prisma-cms'; // 👈 update to your output directory
import { CustomPrismaService } from 'nestjs-prisma';

@Injectable()
export class AppService {
  constructor(
    @Inject('PrismaServiceAuth') // 👈 use unique name to reference
    private prismaAuth: CustomPrismaService<PrismaAuth>,
    @Inject('PrismaServiceCms') // 👈 use unique name to reference
    private prismaCms: CustomPrismaService<PrismaCms>,
  ) {}

  users() {
    return this.prismaAuth.client.user.findMany();
  }

  user(userId: string) {
    return this.prismaAuth.client.user.findFirstOrThrow({
      where: { id: userId },
    });
  }

  posts() {
    return this.prismaCms.client.post.findMany();
  }
}
```

Inspired by @sabinadams [nestjs-prisma-module](https://github.com/sabinadams/nestjs-prisma-module) 🤩.

### CODE REVIEW

**Comment by tupe12334** [comment]
Hi @marcjulian, We looking forward to this PR, and we would love to help if there is any help needed. Do you have an estimation for the release date of this PR?

**Comment by marcjulian** [comment]
Hi @tupe12334 thanks for asking about it. You can already test it out in the latest `dev` release

```bash
npm i nestjs-prisma@0.20.0-dev.1
```

I have the following todos in mind before merging this PR.

- [x] Async configuration `CustomPrismaModule.forRootAsync(...)`
- [x] Updating docs

You are welcome to help out if you like. I cannot promise any release date yet.

**Comment by tupe12334** [comment]
@marcjulian  I can take the async configuration if I can.

**Comment by marcjulian** [comment]
Sounds good to me. Let me know when you need help.

**Comment by marcjulian** [comment]
@tupe12334 I found some time to try out `forRootAsync`. Hope you didn't started yet.

Here is how to use `forRootAsync`

```ts
import { PrismaClient } from '@prisma/client';
import { Module } from '@nestjs/common';
import { CustomPrismaModule } from 'nestjs-prisma';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { CustomPrismaConfig } from './custom-prisma-config';

@Module({
  imports: [
    // factory
    CustomPrismaModule.forRootAsync({
      name: 'PrismaService',
      useFactory: () => {
        const client = new PrismaClient();
        return client;
      },
    }),
    // class
    CustomPrismaModule.forRootAsync({
      name: 'PrismaService',
      useClass: CustomPrismaConfig,
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

```ts
// for useClass: CustomPrismaConfig
import { Injectable } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';
import { CustomPrismaClientFactory } from 'nestjs-prisma';

@Injectable()
export class CustomPrismaConfig
  implements CustomPrismaClientFactory<PrismaClient>
{
  constructor() {
    // TODO inject any other service here like the `ConfigService`
  }

  createPrismaClient(): PrismaClient | Promise<PrismaClient> {
    return new PrismaClient();
  }
}
```

**Pull request merged**
