### PR TITLE
Update prisma to version 4

### LINKED ISSUE #28: support Prisma v4
Hey, is there any intention to support Prisma 4 in the future, and if so, when?
We want to upgrade our platform, but nestjs-prisma  has a peer-dependency with prisma versions "^2.0.0 || ^3.0.0"

Screen Shot 2022-07-18 at 14 59 59

### PR DESCRIPTION
**Pull request by donnguyen**

### CODE REVIEW

**Comment by marcjulian** [comment]
@donnguyen thanks for the update. I will release a dev version for you to test it out.

**Comment by marcjulian** [comment]
Please try it out with the latest dev release:

```bash
npm i nestjs-prisma@0.17.0-dev.0
```

**Comment by donnguyen** [comment]
@marcjulian thanks for such a quick response. We have been tested this in our own project, everything seems to be working perfectly. Cheers

**Comment by drMonro** [comment]
Hello! Trying to lunch nestjs-prisma@0.17.0-dev.0 with "@nestjs/common": "9.0.1" but got dependencies resolve error when making npm install operation.
https://prnt.sc/hPng-1yi-Fud

Made special branch with what situation: https://github.com/drMonro/nextjs-stroyrem/tree/nestjs-prisma-bug

**Comment by marcjulian** [comment]
@drMonro thanks for the info. I updated the peerDeps to support Nest v9. Please give it a try with 

```bash
npm i nestjs-prisma@0.17.0-dev.1
```

**Comment by marcjulian** [comment]
@donnguyen @drMonro I released `0.17.0` with support for Prisma 4 and Nest 9. Thanks again and enjoy.

**Pull request merged**
